# Generated by Django 5.2 on 2025-05-06 17:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('full_address', models.TextField()),
                ('area', models.CharField(max_length=50)),
                ('nid_bcid', models.TextField()),
                ('drive_link', models.TextField()),
                ('verified_yn', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedTutor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tutor_name', models.TextField()),
                ('photo_url', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('display_order', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('photo', models.TextField()),
                ('exp', models.IntegerField()),
                ('edu_qualification', models.TextField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('ssc_school', models.TextField()),
                ('ssc_grade', models.CharField(max_length=10)),
                ('hsc_school', models.TextField()),
                ('hsc_grade', models.CharField(max_length=10)),
                ('uni', models.TextField()),
                ('uni_grade', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('full_address', models.TextField()),
                ('areas_to_tutor', models.TextField()),
                ('fb_link', models.TextField()),
                ('nid_bcid', models.TextField()),
                ('drive_link', models.TextField()),
                ('verified_yn', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('medium', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField()),
                ('time', models.CharField(max_length=100)),
                ('days_per_week', models.IntegerField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subjects', models.TextField()),
                ('medium', models.CharField(max_length=100)),
                ('class_level', models.CharField(max_length=100)),
                ('student_gender', models.CharField(max_length=100)),
                ('gender_preference', models.CharField(default='No Preference', max_length=100)),
                ('monthly_class_wise_pay', models.BooleanField(default=False)),
                ('number_of_students', models.IntegerField(default=1)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.guardian')),
            ],
        ),
        migrations.CreateModel(
            name='PostDeleteJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.admin')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.job')),
            ],
            options={
                'unique_together': {('admin', 'job')},
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.guardian')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.job')),
            ],
            options={
                'unique_together': {('guardian', 'job')},
            },
        ),
        migrations.CreateModel(
            name='ShortList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.job')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tutor')),
            ],
            options={
                'unique_together': {('job', 'tutor')},
            },
        ),
        migrations.CreateModel(
            name='Interacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_yn', models.BooleanField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.job')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tutor')),
            ],
            options={
                'unique_together': {('tutor', 'job')},
            },
        ),
    ]
